import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import SiteShell from "../components/storefront/site-shell";
import { getProduct, getProducts } from "../lib/shopify/products";

export const revalidate=300;
export const metadata:Metadata={title:"ShoreHitch — Anchoring Redefined",description:"Explore ShoreHitch anchoring systems for boating, deep water and crossover outdoor applications. Compare systems, accessories and customization options.",alternates:{canonical:"/"}};
function money(a:string,c:string){return new Intl.NumberFormat("en-US",{style:"currency",currency:c}).format(Number(a))}
const applications=[{title:"Boating & Watersports",copy:"Anchoring systems and accessories for boats, PWCs and your time on the water.",href:"/shop"},{title:"Deep-Water Anchoring",copy:"Discover the Bucket Anchor and review the current configuration for your boating setup.",href:"/products/shorehitch-bucket-pre-order-today"},{title:"Outdoor & Powersports",copy:"Explore crossover applications for outdoor recreation and powersports setups.",href:"/contact"},{title:"Trade Shows & Events",copy:"Discuss compatible anchoring options for displays, events and non-marine setups.",href:"/contact"}];
const whyPoints=[{title:"Purpose-built",copy:"A dedicated anchoring system designed around a cleaner, more intentional setup than improvised hardware."},{title:"Premium materials",copy:"Marine-focused construction, refined finishes and a product family designed to look at home on premium boats."},{title:"Made to personalize",copy:"Color, accessories and engraving let owners configure the system around their boat and setup."},{title:"Backed for the long haul",copy:"ShoreHitch anchor units are backed by a lifetime warranty."}];
const steps=[{number:"01",title:"Position",copy:"Place the ShoreHitch system where your setup calls for it."},{number:"02",title:"Set",copy:"Use the integrated mechanism to establish the anchor in suitable bottom conditions."},{number:"03",title:"Connect",copy:"Secure your line and finish the setup for the conditions around you."}];
const faqs=[{q:"Which ShoreHitch is right for me?",a:"Start with your vessel, anchoring environment and intended use. The comparison tool helps narrow the current systems without guessing compatibility."},{q:"Can I customize my ShoreHitch?",a:"Select products support custom engraving, and the current product pages show available colors and configuration options directly from Shopify."},{q:"How does checkout work?",a:"The storefront uses Shopify for product data, cart, checkout, taxes, discounts, shipping options and order processing."}];

export default async function HomePage(){
 const [catalog,og,baby,bucket]=await Promise.all([getProducts(12).catch(()=>[]),getProduct("shorehitch").catch(()=>null),getProduct("baby-hitch-18-12").catch(()=>null),getProduct("shorehitch-bucket-pre-order-today").catch(()=>null)]);
 const anchors=[og,baby,bucket].filter(Boolean); const featured=catalog.filter(p=>!anchors.some(a=>a?.id===p.id)&&p.handle!=="custom-engraving").slice(0,4);
 return <SiteShell>
 <section className="relative min-h-[760px] overflow-hidden border-b border-white/10 lg:min-h-[calc(100vh-130px)]">
  <video src="https://cdn.shopify.com/s/files/1/0934/6668/9902/files/b_roll_clip_5.m4v?v=1787844877" autoPlay muted loop playsInline className="hero-media absolute inset-0 h-full w-full object-cover" />
  <div className="absolute inset-0 bg-black/24"/><div className="absolute inset-0 bg-gradient-to-r from-black/80 via-black/42 to-transparent"/><div className="absolute inset-0 bg-gradient-to-t from-black/45 via-transparent to-black/10"/>
  <div className="relative mx-auto flex min-h-[760px] max-w-7xl items-center px-5 py-24 md:px-8 lg:min-h-[calc(100vh-130px)]"><div className="max-w-3xl"><div className="mb-6 flex items-center gap-3"><span className="h-px w-8 bg-[#4AC9D3]"/><span className="text-[11px] font-black uppercase tracking-[0.28em] text-[#4AC9D3]">ShoreHitch — Anchoring Redefined</span></div><h1 className="max-w-3xl text-5xl font-extrabold leading-[0.94] tracking-[-0.045em] text-white sm:text-6xl lg:text-[78px]">From shoreline to deep water. <span className="cyan-shimmer">Beyond boating.</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-white/80 md:text-lg">Explore anchoring systems and accessories for boating, outdoor recreation, powersports and trade-show setups. Find the right system for your application—and make it yours.</p><div className="mt-7 flex flex-wrap gap-2">{["Designed in USA","Patent Pending","Lifetime Warranty on Anchor Units"].map(i=><span key={i} className="rounded-full border border-white/25 bg-black/20 px-3.5 py-2 text-[10px] font-bold uppercase tracking-[0.14em] text-white/80 backdrop-blur-sm">{i}</span>)}</div><div className="mt-9 flex flex-wrap gap-3"><Link href="/which-shorehitch" className="cta-pulse inline-flex items-center rounded bg-[#4AC9D3] px-7 py-4 text-sm font-black uppercase tracking-wider text-black hover:bg-[#6DD8E1]">Find Your Anchor <span className="ml-2">→</span></Link><Link href="/shop" className="inline-flex items-center rounded border border-white/35 bg-black/15 px-7 py-4 text-sm font-black uppercase tracking-wider text-white hover:border-[#4AC9D3] hover:text-[#4AC9D3]">Shop All Products</Link></div></div></div>
 </section>
 <section className="border-b border-white/10 bg-[#0A0A0A]"><div className="mx-auto grid max-w-7xl grid-cols-1 gap-px bg-white/8 sm:grid-cols-3">{["Designed in the USA","Patent Pending","Lifetime Warranty on Anchor Units"].map(i=><div key={i} className="bg-[#0A0A0A] px-6 py-5 text-center text-[11px] font-bold uppercase tracking-[0.18em] text-white/60"><span className="mr-2 text-[#4AC9D3]">◆</span>{i}</div>)}</div></section>
 <section className="bg-black py-20 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="max-w-3xl"><div className="mb-4 flex items-center gap-3"><span className="h-px w-7 bg-[#4AC9D3]"/><span className="text-[11px] font-black uppercase tracking-[0.24em] text-[#4AC9D3]">Built for more than one kind of day</span></div><h2 className="text-4xl font-bold tracking-tight md:text-5xl">Start with your application.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{applications.map((i,n)=><Link key={i.title} href={i.href} className="group relative min-h-60 overflow-hidden rounded-xl border border-white/10 bg-[#0A0A0A] p-6 transition hover:-translate-y-1 hover:border-[#4AC9D3]/60"><div className="absolute right-4 top-3 text-6xl font-black text-white/[0.035]">0{n+1}</div><div className="relative flex h-full flex-col justify-end"><div className="text-lg font-bold">{i.title}</div><p className="mt-3 text-sm leading-6 text-white/48">{i.copy}</p><div className="mt-6 text-[11px] font-black uppercase tracking-[0.16em] text-[#4AC9D3]">Explore →</div></div></Link>)}</div></div></section>
 <section className="grid border-y border-white/10 bg-[#0A0A0A] lg:grid-cols-[1.02fr_0.98fr]"><div className="relative min-h-[540px] overflow-hidden"><Image src="https://cdn.shopify.com/s/files/1/0934/6668/9902/files/Blue_Shorehitch.png?v=1787847178" alt="Blue ShoreHitch anchor" fill sizes="(max-width:1024px) 100vw,52vw" className="premium-media object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-transparent"/></div><div className="flex items-center px-6 py-16 md:px-10 lg:px-14"><div className="max-w-xl"><div className="mb-4 flex items-center gap-3"><span className="h-px w-7 bg-[#4AC9D3]"/><span className="text-[11px] font-black uppercase tracking-[0.24em] text-[#4AC9D3]">Why ShoreHitch</span></div><h2 className="text-4xl font-bold tracking-tight md:text-5xl">Premium by design. Simple by intention.</h2><p className="mt-5 text-base leading-7 text-white/58">ShoreHitch is built to feel like part of the boat—not an afterthought in the locker. The system combines refined materials, purposeful setup, personalization and long-term support in one product family.</p><div className="mt-8 grid gap-5 sm:grid-cols-2">{whyPoints.map(p=><div key={p.title} className="border-l border-[#4AC9D3]/45 pl-4"><div className="text-sm font-black uppercase tracking-[0.08em]">{p.title}</div><p className="mt-2 text-sm leading-6 text-white/48">{p.copy}</p></div>)}</div><Link href="/about" className="mt-8 inline-flex text-xs font-black uppercase tracking-[0.16em] text-[#4AC9D3]">Why ShoreHitch →</Link></div></div></section>
 <section className="bg-black py-20 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-4 flex items-center gap-3"><span className="h-px w-7 bg-[#4AC9D3]"/><span className="text-[11px] font-black uppercase tracking-[0.24em] text-[#4AC9D3]">Choose your system</span></div><h2 className="text-4xl font-bold tracking-tight md:text-5xl">Three anchors. Different jobs.</h2></div><Link href="/which-shorehitch" className="text-sm font-bold text-[#4AC9D3]">Compare systems →</Link></div><div className="mt-10 grid gap-5 md:grid-cols-3">{anchors.map((p,n)=>p&&<Link key={p.id} href={`/products/${p.handle}`} className="product-card group overflow-hidden rounded-xl border border-white/10 bg-[#0A0A0A]"><div className="relative aspect-[4/3] overflow-hidden bg-[#111]">{p.featuredImage?<Image src={p.featuredImage.url} alt={p.featuredImage.altText||p.title} fill sizes="(max-width:768px) 100vw,33vw" className="premium-media object-cover transition duration-500 group-hover:scale-[1.025]"/>:null}<span className="absolute left-4 top-4 rounded bg-black/60 px-3 py-1.5 text-[9px] font-black uppercase tracking-[0.18em] text-[#4AC9D3]">{n===0?"Flagship":n===1?"Compact":"Deep Water"}</span></div><div className="p-6"><div className="text-[10px] font-black uppercase tracking-[0.18em] text-[#4AC9D3]">{p.availableForSale?"Available":"Currently unavailable"}</div><h3 className="mt-2 text-2xl font-bold">{p.title}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-white/45">{p.description}</p><div className="mt-6 flex items-center justify-between"><span className="font-black">From {money(p.priceRange.minVariantPrice.amount,p.priceRange.minVariantPrice.currencyCode)}</span><span className="text-xs font-black uppercase text-[#4AC9D3]">View →</span></div></div></Link>)}</div></div></section>
 <section className="bg-[#0A0A0A] py-20 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><div className="mb-4 flex items-center gap-3"><span className="h-px w-7 bg-[#4AC9D3]"/><span className="text-[11px] font-black uppercase tracking-[0.24em] text-[#4AC9D3]">Engineered to be straightforward</span></div><h2 className="text-4xl font-bold md:text-5xl">Position. Set. Connect.</h2><p className="mt-5 max-w-xl text-base leading-7 text-white/52">The exact setup depends on your ShoreHitch model, vessel, bottom conditions and environment. The system is designed around a simple, repeatable deployment process.</p><Link href="/how-it-works" className="mt-7 inline-flex rounded bg-[#4AC9D3] px-5 py-3.5 text-xs font-black uppercase text-black">See How It Works</Link></div><div className="grid gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10 sm:grid-cols-3">{steps.map(s=><div key={s.number} className="bg-black p-6 sm:min-h-64"><div className="text-5xl font-black text-white/[.08]">{s.number}</div><div className="mt-8 text-lg font-bold">{s.title}</div><p className="mt-3 text-sm leading-6 text-white/45">{s.copy}</p></div>)}</div></div></div></section>
 <section className="border-y border-white/10 bg-black py-20 md:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 md:grid-cols-[.85fr_1.15fr] md:px-8"><div><div className="mb-4 flex items-center gap-3"><span className="h-px w-7 bg-[#4AC9D3]"/><span className="text-[11px] font-black uppercase tracking-[0.24em] text-[#4AC9D3]">Customer feedback</span></div><h2 className="text-4xl font-bold">Built for the people who use it.</h2></div><div><p className="text-lg leading-8 text-white/58">Read published ShoreHitch customer feedback from our review history. Ratings and review content stay tied to the real review dataset rather than manufactured testimonials.</p><Link href="/reviews" className="mt-6 inline-block text-sm font-black uppercase text-[#4AC9D3]">Read Reviews →</Link></div></div></section>
 {featured.length>0&&<section className="bg-[#0A0A0A] py-20 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="flex items-end justify-between gap-5"><div><div className="text-[11px] font-black uppercase tracking-[0.24em] text-[#4AC9D3]">Complete the setup</div><h2 className="mt-3 text-4xl font-bold">Accessories & personalization</h2></div><Link href="/shop" className="hidden text-sm font-bold text-[#4AC9D3] sm:block">Shop all →</Link></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{featured.map(p=><Link key={p.id} href={`/products/${p.handle}`} className="product-card overflow-hidden rounded-xl border border-white/10 bg-black"><div className="relative aspect-square overflow-hidden bg-[#111]">{p.featuredImage&&<Image src={p.featuredImage.url} alt={p.featuredImage.altText||p.title} fill sizes="(max-width:640px) 100vw,25vw" className="premium-media object-cover"/>}</div><div className="p-4"><div className="font-bold">{p.title}</div><div className="mt-2 text-sm text-white/50">{money(p.priceRange.minVariantPrice.amount,p.priceRange.minVariantPrice.currencyCode)}</div></div></Link>)}</div></div></section>}
 <section className="bg-black py-20 md:py-24"><div className="mx-auto max-w-5xl px-5 md:px-8"><div className="text-center"><div className="text-[11px] font-black uppercase tracking-[0.24em] text-[#4AC9D3]">Questions before you buy?</div><h2 className="mt-3 text-4xl font-bold md:text-5xl">The essentials, answered.</h2></div><div className="mt-10 divide-y divide-white/10 border-y border-white/10">{faqs.map(f=><details key={f.q} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-lg font-bold">{f.q}<span className="text-[#4AC9D3]">+</span></summary><p className="mt-4 max-w-3xl text-sm leading-7 text-white/50">{f.a}</p></details>)}</div><div className="mt-8 text-center"><Link href="/faq" className="text-sm font-black uppercase text-[#4AC9D3]">View All FAQs →</Link></div></div></section>
 <section className="border-t border-white/10 bg-[#0A0A0A] py-20"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="relative overflow-hidden rounded-2xl border border-[#4AC9D3]/25 bg-black p-8 md:p-12"><div className="absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(circle_at_center,rgba(74,201,211,.12),transparent_60%)]"/><div className="relative max-w-3xl"><div className="text-[11px] font-black uppercase tracking-[0.24em] text-[#4AC9D3]">Built around your setup</div><h2 className="mt-3 text-4xl font-bold md:text-5xl">Find the ShoreHitch that fits how you use the water.</h2><p className="mt-5 text-base leading-7 text-white/52">Compare current systems or tell us about your boat and application. We’ll keep recommendations tied to the actual configuration.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/which-shorehitch" className="rounded bg-[#4AC9D3] px-6 py-3.5 text-sm font-black uppercase text-black">Compare Anchors</Link><Link href="/contact" className="rounded border border-white/20 px-6 py-3.5 text-sm font-black uppercase">Discuss Your Setup</Link></div></div></div></div></section>
 </SiteShell>;
}
