import Link from "next/link";
import Image from "next/image";

export const metadata={title:"Why ShoreHitch | ShoreHitch",description:"Compare ShoreHitch with traditional spikes, augers and fluke anchors."};

const rows=[
 {label:"Setup",sh:"In seconds — slide hammer",spike:"Hammer or push required",auger:"Slow & tiring twisting into sand"},
 {label:"Holding Power",sh:"Holds up to 40 ft vessels with one unit — lifetime warranty backed",spike:"Too heavy for finer sands — sinks, falls, and drags over time",auger:"Struggles in packed or coarse sand"},
 {label:"Durability",sh:"Aerospace-grade aluminum & 316 stainless steel — lifetime warranty",spike:"Steel bends or rusts easily in saltwater",auger:"Threads and handles seize or strip"},
 {label:"Storage",sh:"Dedicated storage system",spike:"Bulky, often tossed in lockers",auger:"Muddy & awkward to store"},
 {label:"Aesthetic",sh:"Premium customizable design",spike:"Plain utility look",auger:"Basic hardware-store appearance"},
];

export default function WhyShoreHitchPage(){return <main className="bg-black text-white">
 <section className="border-b border-white/10 bg-[#050505] px-5 py-20 md:py-28"><div className="mx-auto max-w-6xl text-center"><div className="mb-4 flex items-center justify-center gap-3"><span className="h-px w-7 bg-[#4AC9D3]"/><span className="text-xs font-bold uppercase tracking-[.22em] text-[#4AC9D3]">Why ShoreHitch</span><span className="h-px w-7 bg-[#4AC9D3]"/></div><h1 className="text-4xl font-black tracking-tight md:text-6xl">Why Upgrade From Traditional<br className="hidden md:block"/> Spikes &amp; Fluke Anchors?</h1><p className="mx-auto mt-6 max-w-3xl text-base font-medium leading-relaxed text-white/65 md:text-lg">ShoreHitch was built to replace the frustrating parts of traditional shoreline anchoring with a cleaner, faster and more refined system designed around real boating use.</p></div></section>

 <section className="border-b border-white/10 px-4 py-16 md:px-6 md:py-20"><div className="mx-auto max-w-5xl overflow-x-auto pb-3"><div className="min-w-[760px]">
  <div className="mb-6 grid grid-cols-4 gap-4 items-stretch"><div/><div className="flex flex-col overflow-hidden rounded-xl border-2 border-[#4AC9D3]/40 bg-[#4AC9D3]/10"><div className="flex flex-1 items-center justify-center bg-black p-5"><Image src="https://cdn.shopify.com/s/files/1/0934/6668/9902/files/ShoreHitch-03.png?v=1783102739" alt="ShoreHitch" width={420} height={170} className="h-auto w-full object-contain"/></div><span className="py-3 text-center text-xs font-bold uppercase tracking-widest text-[#4AC9D3]">ShoreHitch</span></div><div className="flex flex-col items-center justify-center rounded-xl border border-white/10 bg-white/[.03] p-5 text-center"><span className="text-4xl">🔩</span><span className="mt-2 text-[10px] leading-snug text-white/35">Many competitors, no warranties</span><span className="mt-4 text-xs font-bold uppercase tracking-widest text-white/55">Traditional Spikes</span></div><div className="flex flex-col items-center justify-center rounded-xl border border-white/10 bg-white/[.03] p-5 text-center"><span className="text-4xl">⚓</span><span className="mt-2 text-[10px] leading-snug text-white/35">Bulky &amp; heavy. Drags and slides over time. Multiple adjustments during anchoring.</span><span className="mt-4 text-xs font-bold uppercase tracking-widest text-white/55">Augers / Fluke Anchors</span></div></div>
  {rows.map((row,i)=><div key={row.label} className={`grid grid-cols-4 gap-4 border-b border-white/10 py-4 ${i%2?"bg-white/[.015]":""}`}><div className="flex items-center"><span className="text-xs font-bold uppercase tracking-widest text-[#4AC9D3]">{row.label}</span></div><div className="flex items-center gap-2 rounded-lg bg-[#4AC9D3]/5 px-3 py-3"><span className="font-black text-[#4AC9D3]">✓</span><span className="text-sm font-semibold text-white">{row.sh}</span></div><div className="flex items-center gap-2 px-3 py-3"><span className="text-red-400">✕</span><span className="text-sm text-white/55">{row.spike}</span></div><div className="flex items-center gap-2 px-3 py-3"><span className="text-red-400">✕</span><span className="text-sm text-white/55">{row.auger}</span></div></div>)}
 </div></div><div className="mt-10 text-center"><Link href="/shop" className="inline-flex rounded bg-[#4AC9D3] px-12 py-4 text-sm font-black uppercase tracking-wider text-black transition hover:bg-[#6DD8E1]">Shop Now</Link></div></section>

 <section className="px-5 py-20 md:py-28"><div className="mx-auto grid max-w-6xl gap-12 md:grid-cols-2 md:items-center"><div><div className="mb-4 flex items-center gap-3"><span className="h-px w-7 bg-[#4AC9D3]"/><span className="text-xs font-bold uppercase tracking-[.22em] text-[#4AC9D3]">Why ShoreHitch</span></div><h2 className="text-4xl font-black tracking-tight md:text-5xl">We Build What the<br/><span className="text-[#4AC9D3]">Industry Won't.</span></h2><p className="mt-6 text-base font-medium leading-relaxed text-white/65">Every ShoreHitch product starts from a real problem we lived as boaters: dragging anchors, awkward setups and generic hardware that quits. We engineered a more refined system — patent pending, designed in the USA and backed by a lifetime warranty on ShoreHitch anchor units.</p></div><div className="grid gap-3">{["Integrated slide-hammer design for fast, straightforward setting.","Marine-focused materials selected for demanding boating environments.","Premium colors and personalization options.","Lifetime warranty on ShoreHitch anchor units.","Designed in the USA by a family-owned boating brand."].map(x=><div key={x} className="flex gap-3 rounded-xl border border-white/10 bg-[#0A0A0A] p-4"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full border border-[#4AC9D3]/40 bg-[#4AC9D3]/10 text-sm font-black text-[#4AC9D3]">✓</span><span className="font-semibold leading-relaxed text-white/80">{x}</span></div>)}</div></div></section>
 </main>}
