"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import CartLink from "../cart/cart-link";

const links=[{href:"/",label:"Home"},{href:"/shop",label:"Shop"},{href:"/which-shorehitch",label:"Which ShoreHitch?"},{href:"/how-it-works",label:"How It Works"},{href:"/reviews",label:"Reviews"},{href:"/dealer",label:"Become a Dealer"},{href:"/contact",label:"Contact"}];
function SearchIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" className="h-4 w-4" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg>}
function MenuIcon({open}:{open:boolean}){return open?<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" className="h-5 w-5" aria-hidden="true"><path d="M5 5l14 14M19 5 5 19"/></svg>:<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" className="h-5 w-5" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg>}
export default function BrandHeader(){const[open,setOpen]=useState(false);return <><div className="border-b border-black/10 bg-[#4AC9D3] text-black"><div className="mx-auto flex min-h-9 max-w-[1440px] items-center justify-center gap-3 px-5 text-center text-[10px] font-bold uppercase tracking-[.2em] md:text-[11px]"><Image src="https://cdn.shopify.com/s/files/1/0934/6668/9902/files/ShoreHitch-02.png?v=1783443368" alt="" width={58} height={24} className="h-6 w-auto object-contain"/><span>Designed in the USA · Patent Pending · Lifetime Warranty on Anchor Units</span></div></div><header className="sticky top-0 z-50 border-b border-white/10 bg-black/95 backdrop-blur-xl"><div className="mx-auto flex h-[104px] max-w-[1440px] items-center justify-between gap-4 px-5 md:h-[116px] md:px-8"><Link href="/" aria-label="ShoreHitch home" className="flex min-w-0 items-center"><Image src="https://cdn.shopify.com/s/files/1/0934/6668/9902/files/ShoreHitch-03.png?v=1783102739" alt="ShoreHitch — Anchoring Redefined" width={480} height={186} priority className="h-[128px] w-auto max-w-[300px] object-contain object-left sm:max-w-[350px] md:h-[148px] md:max-w-[390px] 2xl:max-w-[430px]"/></Link><nav aria-label="Primary navigation" className="hidden items-center gap-3 2xl:gap-4 xl:flex">{links.slice(1).map(link=><Link key={link.href} href={link.href} className={`whitespace-nowrap text-[12px] 2xl:text-[13px] font-semibold tracking-wide transition ${link.href==="/dealer"?"text-[#4AC9D3]":"text-white/65 hover:text-[#4AC9D3]"}`}>{link.label}</Link>)}</nav><div className="flex shrink-0 items-center gap-2.5"><Link href="/search" aria-label="Search" className="hidden p-2 text-white/50 hover:text-white md:block"><SearchIcon/></Link><CartLink/><Link href="/shop" className="hidden rounded bg-[#4AC9D3] px-4 py-2.5 text-xs font-black uppercase tracking-wider text-black hover:bg-[#6DD8E1] md:inline-flex">Shop Now</Link><button type="button" aria-expanded={open} aria-controls="mobile-menu" aria-label={open?"Close menu":"Open menu"} onClick={()=>setOpen(v=>!v)} className="rounded border border-white/10 p-2.5 text-white/70 xl:hidden"><MenuIcon open={open}/></button></div></div>{open?<nav id="mobile-menu" aria-label="Mobile navigation" className="border-t border-white/10 bg-[#0A0A0A] px-5 py-5 xl:hidden"><div className="mx-auto flex max-w-7xl flex-col">{links.map(link=><Link key={link.href} href={link.href} onClick={()=>setOpen(false)} className={`border-b border-white/8 py-3.5 text-sm font-semibold last:border-b-0 ${link.href==="/dealer"?"text-[#4AC9D3]":"text-white/75"}`}>{link.label}</Link>)}<Link href="/search" onClick={()=>setOpen(false)} className="mt-3 rounded border border-white/15 px-4 py-3 text-center text-xs font-bold uppercase tracking-wider text-white">Search</Link><Link href="/shop" onClick={()=>setOpen(false)} className="mt-2 rounded bg-[#4AC9D3] px-4 py-3.5 text-center text-xs font-black uppercase tracking-wider text-black">Shop Now</Link></div></nav>:null}</header></>}
