import Image from "next/image";
import { figmaMedia } from "../../lib/figma-media";

type Block={eyebrow:string;title:string;intro:string;points:string[]};
const CONTENT:Record<string,Block>={
 "shorehitch-bucket-pre-order-today":{eyebrow:"Bucket Anchor",title:"Built for the deeper-water side of ShoreHitch.",intro:"The Bucket Anchor extends the ShoreHitch family beyond shoreline and sandbar use with a substantial stainless-steel system designed around deep-water anchoring and transport-friendly handling.",points:["316 stainless-steel construction","Mirror-polished marine finish","Pivoting transport handle","Designed as the deep-water anchor in the ShoreHitch system"]},
 "360-anchor-swivel":{eyebrow:"360° Anchor Swivel",title:"Keep the connection moving cleanly.",intro:"The swivel is designed as a compact connection point for ShoreHitch setups where line rotation and hardware organization matter.",points:["Full 360° rotating connection","Marine-grade stainless construction","Compact add-on for ShoreHitch anchor setups","Designed for simple integration with your existing line setup"]},
 "custom-dock-lines-pair":{eyebrow:"Custom Dock Lines",title:"Dock lines built to look as intentional as the boat.",intro:"ShoreHitch dock lines pair practical marine use with a more premium, personalized presentation for owners who care about the full setup.",points:["Double-braid nylon construction","Hand-finished presentation","Custom engraving options where offered","Built for everyday dock and marina use"]},
 "shorehook-tether-adjuster":{eyebrow:"ShoreHook",title:"Fine-tune your line without reworking the whole setup.",intro:"The ShoreHook gives owners a compact way to adjust and organize tether positioning around the ShoreHitch system.",points:["Tool-free adjustment approach","Stainless hardware","Compact form factor","Designed to simplify line positioning"]},
 "dry-bag-storage":{eyebrow:"Hard Case",title:"Protect the ShoreHitch between days on the water.",intro:"A dedicated storage case keeps the system contained, cleaner and easier to transport instead of treating premium hardware like loose locker gear.",points:["Dedicated ShoreHitch storage","Structured protection for transport","Cleaner onboard organization","Built around the ShoreHitch form factor"]},
 "custom-engraving":{eyebrow:"Custom Engraving",title:"Make the anchor unmistakably yours.",intro:"Personalization is one of the signature parts of the ShoreHitch experience. Add text or a custom logo where supported and carry that identity through the finished system.",points:["Text personalization","Custom logo upload support","Permanent laser-etched presentation","Designed to ship with the configured ShoreHitch order"]},
 "soft-top-handle-dek-x":{eyebrow:"Soft Top",title:"A finished touch for the handle.",intro:"The Soft Top is a small accessory that adds protection and a more finished look to the ShoreHitch handle area.",points:["Protective finishing accessory","Compact add-on","Designed for ShoreHitch anchor units","Available as an add-on during anchor configuration"]}
};
const ALREADY_DETAILED=new Set(["shorehitch","baby-hitch-18-12"]);
export default function ProductEducation({handle}:{handle:string}){if(ALREADY_DETAILED.has(handle))return null;const block=CONTENT[handle];if(!block)return null;const media=figmaMedia(handle).filter(m=>m.type==="image").slice(0,3);return <section className="border-t border-white/10 bg-[#050505]"><div className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-20"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><div className="mb-4 flex items-center gap-3"><span className="h-px w-7 bg-[#4AC9D3]"/><span className="text-[11px] font-black uppercase tracking-[.22em] text-[#4AC9D3]">{block.eyebrow}</span></div><h2 className="text-3xl font-black tracking-tight md:text-4xl">{block.title}</h2><p className="mt-5 max-w-xl text-base font-medium leading-7 text-white/62">{block.intro}</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{block.points.map(p=><div key={p} className="flex gap-3 rounded-xl border border-white/10 bg-[#0A0A0A] p-4"><span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full border border-[#4AC9D3]/35 bg-[#4AC9D3]/10 text-[10px] font-black text-[#4AC9D3]">✓</span><span className="text-sm font-semibold leading-6 text-white/75">{p}</span></div>)}</div></div>{media.length?<div className={`grid gap-3 ${media.length>1?"grid-cols-2":"grid-cols-1"}`}>{media.map((m,i)=><div key={m.src} className={`relative overflow-hidden rounded-xl border border-white/10 bg-[#111] ${i===0&&media.length>2?"col-span-2 aspect-[16/9]":"aspect-square"}`}><Image src={m.src} alt={`${block.eyebrow} detail ${i+1}`} fill sizes="(max-width:1024px) 100vw,50vw" className="premium-media object-cover"/></div>)}</div>:null}</div></div></section>}
