import type { Metadata } from "next";
import Image from "next/image";
import LeadForm from "../components/lead-form";
import SiteShell from "../../components/storefront/site-shell";

export const metadata:Metadata={title:"Become a ShoreHitch Dealer",description:"Apply to become an authorized ShoreHitch dealer or partner.",alternates:{canonical:"/dealer"}};
const benefits=["Fast shipping and support (international available)","MAP pricing enforcement","Marketing assets included","Dedicated dealer support team","Store logo engraving on soft top for brand visibility","Product training and onboarding"];
const industries=["⚓|Marinas & Boat Clubs","🏪|Marine Retailers","🛥️|Boat Dealers","🏄|Watersports Shops","🏕️|Outdoor & Lifestyle","🎁|Gift & Specialty","🏆|Tournament Sponsors","🌎|International Partners"];
const reasons=[
 ["01","Territory Exclusivity","Be the only authorized ShoreHitch dealer in your market. First to apply, first to lock in. We cap dealers per region — no exceptions."],
 ["02","Ground-Floor Momentum","ShoreHitch is in early release. You get in before national retail, before widespread press, and before your competitors realize what they missed."],
 ["03","Untapped Demand","Our customers are already searching. Every boater in your area who discovers ShoreHitch should be buying it through you — not online past you."]
];
export default function DealerPage(){return <SiteShell>
<section className="relative min-h-[610px] overflow-hidden border-b border-white/10 bg-black"><Image src="https://cdn.shopify.com/s/files/1/0934/6668/9902/files/shorehitch-2025-tom-leigh--37.jpg?v=1783627028" alt="ShoreHitch dealer program" fill priority sizes="100vw" className="premium-media object-cover opacity-45"/><div className="absolute inset-0 bg-gradient-to-r from-black/90 via-black/65 to-black/20"/><div className="relative mx-auto flex min-h-[610px] max-w-7xl items-center px-6 py-20"><div className="max-w-2xl"><div className="mb-5 flex items-center gap-3"><span className="h-px w-6 bg-[#4AC9D3]"/><span className="text-xs font-bold uppercase tracking-[.2em] text-[#4AC9D3]">Partner Program</span></div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#4AC9D3]/30 bg-[#4AC9D3]/15 px-4 py-2"><span className="h-2 w-2 rounded-full bg-[#4AC9D3]"/><span className="text-xs font-black uppercase tracking-[.15em] text-[#4AC9D3]">Limited Spots Per Region</span></div><h1 className="text-4xl font-black leading-[1.06] tracking-tight md:text-6xl">Become the First<br/><span className="steel-text">ShoreHitch Dealer</span><br/>In Your Area.</h1><p className="mt-6 max-w-xl text-lg font-semibold leading-8 text-white/75">Early release partners gain untapped market visibility — before the competition even knows we exist.</p><p className="mt-3 max-w-xl text-base font-semibold leading-7 text-white/55">We're selectively onboarding a limited number of dealers per region. Once your area is claimed, it's closed.</p><div className="mt-7 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-white/70"><span>🇺🇸 Designed In The USA</span><span>⚙️ Patent Pending</span><span>🛡️ Lifetime Warranty on Anchors</span></div><a href="#apply" className="mt-9 inline-flex rounded bg-[#4AC9D3] px-8 py-4 text-sm font-black uppercase tracking-widest text-black transition hover:bg-[#6dd8e1]">Fill Out Your Dealer Info Sheet →</a></div></div></section>
<section className="relative overflow-hidden border-b border-white/10 bg-[#1a1e24] py-20"><div className="pointer-events-none absolute right-0 top-1/2 -translate-y-1/2 opacity-[.035]"><Image src="https://cdn.shopify.com/s/files/1/0934/6668/9902/files/ShoreHitch-02.png?v=1783443368" alt="" width={420} height={420}/></div><div className="relative mx-auto max-w-7xl px-6"><div className="text-center"><h2 className="text-3xl font-black tracking-tight md:text-5xl">Dealer Benefits That Drive Sales.</h2><p className="mx-auto mt-3 max-w-xl text-base font-semibold text-white/60">ShoreHitch is more than a product. It's a lifestyle brand, trusted by boaters nationwide.</p></div><div className="mx-auto mt-12 grid max-w-3xl gap-x-16 gap-y-6 md:grid-cols-2">{benefits.map((text,i)=><div key={text} className="flex items-start gap-3"><span className="text-lg text-[#4AC9D3]">{["🚚","📊","📦","🎧","⚡","🎓"][i]}</span><span className="text-base font-semibold leading-7 text-white/75">{text}</span></div>)}</div><div className="mt-12 text-center"><a href="#apply" className="inline-flex rounded bg-[#4AC9D3] px-10 py-4 text-sm font-black uppercase tracking-widest text-black hover:bg-[#6dd8e1]">Fill Out Your Info Sheet →</a></div></div></section>
<section className="mx-auto max-w-7xl border-b border-white/10 px-6 py-16"><div className="text-center"><div className="flex items-center justify-center gap-3"><span className="h-px w-6 bg-[#4AC9D3]"/><span className="text-xs font-bold uppercase tracking-[.2em] text-[#4AC9D3]">Who We Work With</span><span className="h-px w-6 bg-[#4AC9D3]"/></div><h2 className="mt-3 text-3xl font-black">Open to All Industries</h2><p className="mt-3 text-base font-semibold text-white/55">Bulk pricing available for qualified partners inside and outside the marine industry.</p></div><div className="mt-10 grid grid-cols-2 gap-4 md:grid-cols-4">{industries.map(item=>{const[icon,label]=item.split("|");return <div key={label} className="rounded-xl border border-white/10 bg-[#0A0A0A] p-5 text-center transition hover:border-[#4AC9D3]/30"><div className="text-3xl">{icon}</div><div className="mt-3 text-sm font-bold text-white/75">{label}</div></div>})}</div></section>
<section className="border-y border-[#4AC9D3]/20 bg-gradient-to-r from-[#4AC9D3]/10 via-[#0044FE]/10 to-[#4AC9D3]/10 py-16"><div className="mx-auto max-w-7xl px-6"><div className="text-center"><div className="flex items-center justify-center gap-3"><span className="h-px w-6 bg-[#4AC9D3]"/><span className="text-xs font-bold uppercase tracking-[.2em] text-[#4AC9D3]">Why Partner Now?</span><span className="h-px w-6 bg-[#4AC9D3]"/></div><h2 className="mt-3 text-3xl font-black">Early Partners Win. Here's Why.</h2></div><div className="mt-10 grid gap-6 md:grid-cols-3">{reasons.map(([number,title,body])=><article key={number} className="rounded-2xl border border-white/10 bg-black/40 p-7"><div className="text-3xl font-black text-[#4AC9D3]/65">{number}</div><h3 className="mt-4 text-xl font-black">{title}</h3><p className="mt-3 text-base font-medium leading-7 text-white/65">{body}</p></article>)}</div><div className="mt-10 text-center"><a href="#apply" className="inline-flex rounded bg-white px-9 py-4 text-sm font-black uppercase tracking-widest text-black hover:bg-white/90">Claim Your Territory →</a></div></div></section>
<section id="apply" className="mx-auto max-w-3xl scroll-mt-28 px-6 py-20"><div className="mb-10 text-center"><div className="flex items-center justify-center gap-3"><span className="h-px w-6 bg-[#4AC9D3]"/><span className="text-xs font-bold uppercase tracking-[.2em] text-[#4AC9D3]">Dealer Info Sheet</span><span className="h-px w-6 bg-[#4AC9D3]"/></div><h2 className="mt-3 text-3xl font-black md:text-4xl">Fill Out Your Dealer Info Sheet</h2><p className="mt-3 text-base font-semibold text-white/55">Tell us about your business and we'll reach out within 2 business days. Spots are limited — don't wait.</p></div><div className="rounded-2xl border border-white/10 bg-[#0A0A0A] p-6 md:p-8"><LeadForm type="dealer"/></div><p className="mt-4 text-center text-xs font-medium text-white/35">All applications are subject to review and approval. Submitting does not guarantee a dealership. Expect a response within 2 business days.</p></section>
</SiteShell>}
